language: c

before_script:
- CODENAME=$(lsb_release -cs)
- echo "deb https://packages.wazuh.com/apt $CODENAME main" | tee /etc/apt/sources.list.d/wazuh.listV
- echo "deb http://packages.wazuh.com.s3-website-us-west-1.amazonaws.com/3.x/apt/ unstable main"
- apt-get update
- apt-get install wazuh-manager=2.0-1$CODENAME
- apt-get install wazuh-manager
